### PR TITLE
Option to display values below QRcode (Fix #4)

### LINKED ISSUE #4: add option to display text beside qrcode
Add option to define what display and where display (under, beside..). see http://www.glpi-project.org/forum/viewtopic.php?pid=187922#p187922

I comment form old forge:
I'm write patch for add field. Maybe add to plugin?
Link to patch - http://www.glpi-project.org/forum/viewtopic.php?pid=199763#p199763

### PR DESCRIPTION
**Pull request by mathieumd**
Massively based on the work of tcse10 [in the forum](http://forum.glpi-project.org/viewtopic.php?pid=206915#p206915).

### CODE REVIEW

**Comment by trasher** [comment]
I'm not developer on the current plugin but:
- you have CS issues to fix (see travs build details)
- as far as I've seen, you update the SQL schema, but you did not handle the upgrad part.

**Comment by mathieumd** [comment]
Thanks for your comment @trasher. Could you look at the migration code please; I'm not confident at all on how to achieve that...

**Comment by trasher** [comment]
Hi @mathieumd ; your migration code seems correct; `executeMigration` should probably not be called where you did; but as I've said, I'm not developper on the plugin, dunno how this is handled. Ping @ddurieux

**Comment by cedric-anne** [comment]
Ping @ddurieux

**Comment by informaticavera** [comment]
hello, first of all I apologize for my english, I'm using the google translator.

we have uploaded all your modifications to the glpi plugin but we see an error that we do not know how to solve:

PHP Fatal error: Cannot declare class Cezpdf, because the name is already in use in /usr/share/glpi/plugins/barcode/lib/ezpdf/class.ezpdf.php on line 0, referer: http://....../glpi/front/computer.php

We would be very grateful if you can help us

**Comment by ddurieux** [comment]
Merged manually

**Pull request closed without merging**
